### ISSUE TITLE
[Bug] NGX Datatable Table length

### ISSUE THREAD

**Issue by smolnetim** [creativetimofficial/ct-black-dashboard-pro-angular#2]
### Version
1.0.0
### Reproduction link
https://demos.creative-tim.com/black-dashboard-pro-angular/#/tables/ngx-datatable
### Operating System
Windows 10 Pro
### Device
Desktop PC
### Browser & Version
Chrome 80
### Steps to reproduce
1. Access the link above
2. Select the second page
3. Select more than 10 entries
4. Select 10 entries
### What is expected?
Table contains 10 entries
### What is actually happening?
Table contains more than 10 entries

---

**Comment by smolnetim** [comment]
Issue is still relevant

**Comment by EINazare** [comment]
Hello there, @smolnetim ,

Thank you for your interest in working with our products and sorry for this late reply.
Somehow, my colleagues did not see your issue, or maybe they did not receive an email from Github with your issue, once again I am sorry for this late reply.

To solve your issues, please go inside `src/app/pages/examples/tables/ngxdatatables/ngxdatatables.component.ts` and change `this.entries = $event.target.value;` to `this.entries = parseInt($event.target.value,10);`.

Let me know if you have further issues.

Best,
Manu

**Comment by smolnetim** [comment]
Thanks, that fixed it
