### ISSUE TITLE
[Bug] Left sidebar close option does not work correctly

### ISSUE THREAD

**Issue by telco2011** [creativetimofficial/ct-black-dashboard-pro-angular#7]
### Version
1.1.1
### Reproduction link
https://demos.creative-tim.com/black-dashboard-pro-angular/#/dashboard
### Operating System
Linux or Mac
### Device
Desktop
### Browser & Version
Epiphany or Safari
### Steps to reproduce
1. Open the [demo link](https://demos.creative-tim.com/black-dashboard-pro-angular/#/dashboard) with Safari browser.
2. Change the Safari windows size to have a size under 1200px of width. This action transforms the sidebar.
3. Open the sidebar and try to close it again.
### What is expected?
I would expect to close the sidebar but it does not happen.
### What is actually happening?
I am not able to close the sidebar until I refresh the browser.

---
### Solution
I have seen that in your 'navbar.component.ts' there is a sidebarOpen method. I think this logic works fine with Chrome and Firefox because they are using different render engines than Safari (or Epiphany in Linux). I have tried to review this code but maybe you are faster solving the problem than me.
### Additional comments
This rare behavior also happens in some iPads.

**Comment by telco2011** [comment]
I also attach the screenshot:
![image](https://user-images.githubusercontent.com/3685073/84496766-d1f47500-acad-11ea-94fb-a2560174e362.png)
![image](https://user-images.githubusercontent.com/3685073/84496792-dfa9fa80-acad-11ea-8248-ee5f5be6c22a.png)

After the sidebar is opened, I am not able to close it again.

**Comment by rarestoma** [comment]
Hi @telco2011,

Thank you for working with our products.

I tried to replicate it and it is working on my computer. I am using 13.0.4 version. Can you please tell me what version are you using?

Thank you,
Rares

**Comment by telco2011** [comment]
Hi @rarestoma,

I'm using Safari 13.1 with macOS Catalina v10.15.4.

Also, I've used the responsive mode and it doesn't work for the following modes:
* iPad (7.9")
* iPad mini (9.7")
* iPad Pro (10.5")
For iPhone seems that it works fine as well.

Thanks

**Comment by telco2011** [comment]
Hi @rarestoma,

Any update on this issue?

Thanks

**Comment by rarestoma** [comment]
Hi @telco2011,

Sorry for my late response.

I check and I found that this is not working between 1200px and 991px. Please change at line 46 of `src/assets/scss/black-dashboard/angular-differences/_sidebar-and-main-panel.scss` `@media screen and (max-width: 991px)` with `@media screen and (max-width: 1200px)`.

Please let me know if it works.

Thank you,
Rares

**Comment by telco2011** [comment]
Now it works fine.

Thanks :smiley:
